# Generated by Django 3.1 on 2021-02-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0116_rearport_max_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('files', models.FileField(blank=True, null=True, upload_to='configs')),
                ('config_date', models.DateTimeField(null=True)),
                ('session', models.CharField(max_length=100, null=True)),
                ('config_type', models.CharField(max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.device')),
            ],
            options={
                'verbose_name': 'Configuration Files Historie',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Tracelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('trace_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcim.config')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
